### ISSUE TITLE
Crash on rule with no ref attribute

### ISSUE THREAD

**Issue by pbludov** [asarkar/pmd-migration-tool#2]
A rule like that
```
<rule name="CheckstyleCustomShortVariable"
      message="Avoid variables with short names that shorter than 2 symbols: {0}"
      language="java"
      class="net.sourceforge.pmd.lang.rule.XPathRule"
      externalInfoUrl="">
<description>
   Fields, local variables, or parameter names that are very short are not helpful to the reader.
</description>
<priority>3</priority>
<properties>
   <property name="xpath">
       <value>
           <![CDATA[
 //VariableDeclaratorId[string-length(@Image) < 2]
 [not(ancestor::ForInit)]
 [not(../../VariableDeclarator and ../../../LocalVariableDeclaration and ../../../../ForStatement)]
 [not((ancestor::FormalParameter) and (ancestor::TryStatement))]
 [not(ancestor::ClassOrInterfaceDeclaration[//MarkerAnnotation/Name[pmd-java:typeof(@Image, 'java.lang.Override', 'Override')]])]
            ]]>
       </value>
   </property>
</properties>
</rule>
```
will crash the tool with error message
```
Exception in thread "main" java.lang.IllegalStateException: outer.ref must not be null
	at org.abhijitsarkar.kotlin.pmd.Migrator$toRules$1.doResume(Migrator.kt:86)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The whole file is here:
https://github.com/checkstyle/checkstyle/blob/master/config/pmd.xml

**Comment by asarkar** [comment]
I'll take a look but PRs are always welcome.

**Comment by asarkar** [comment]
@pbludov I made a fix on branch [issue-2](https://github.com/asarkar/pmd-migration-tool/tree/issue-2). Check it out and let me know.

**Comment by pbludov** [comment]
Now it works fine. Thank you, @asarkar!
