### ISSUE TITLE
TypeCastException

### ISSUE THREAD

**Issue by FriedrichFroebel** [asarkar/pmd-migration-tool#4]
I am getting a `TypeCastException`:

```
2018-05-26 17:03:28.197 [ForkJoinPool.commonPool-worker-1] [WARN ] o.a.p.Migrator - Rule: GuardLogStatementJavaUtil has been renamed to: GuardLogStatement
Exception in thread "main" kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
        at org.abhijitsarkar.pmd.Migrator$toRules$1.doResume(Migrator.kt:114)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I could break my XML file down to the following:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="ruleset"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

    <rule ref="rulesets/java/logging-java.xml">
        <exclude name="GuardLogStatementJavaUtil" />
    </rule>

</ruleset>
```

Without the exclude everything runs fine.

**Comment by asarkar** [comment]
Thanks for the report. Fixed in v1.0.2

P.S: Your ruleset isn't valid as shown, it's missing a `description` element.
